version: "2"

services:
  api:
    container_name: api
    build:
      context: ./api/
    ports:
      - "8000:8000"
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend/
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - staticfiles:/app/demo/build
  nginx:
    container_name: nginx
    build:
      context: ./nginx/
    ports:
      - "80:80"
    volumes:
      - staticfiles:/app/demo/build
volumes:
  staticfiles:
